version: '3.9'
services:
  server:
    build: .
    # image: rajeev770/ebb_server:latest
    container_name: ett_server
    ports:
      - '5005:5005'
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: ebb_database
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
