###
//Register
POST http://localhost:5005/moderator/register
Content-Type: application/json

{
    "username" : "LTW Tech",
    "address" : "Milan, Italy",
    "company" : "LTW Technologies",
    "company_type" : "Software",
    "website" : "www.ltwtech.it",
    "authority" : {"role" : ["client"]},
    "phone_no" : "0123456789",
    "email" : "client@ltwtech.it",
    "password" : "1234",
    "avatar" : "1667793288133-668-6689202_avatar-profile-hd-png-download.png"
}

###
//Login
POST http://localhost:5005/moderator/login
Content-Type: application/json

{
    "email" : "client@ltwtech.it",
    "password" : "1234",
    "signedIn" : false
}

###
//Get Admin
GET http://localhost:5005/moderator/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiYXZhdGFyIjoiMTY2Nzc5MzI4ODEzMy02NjgtNjY4OTIwMl9hdmF0YXItcHJvZmlsZS1oZC1wbmctZG93bmxvYWQucG5nIiwidXNlcm5hbWUiOiJMVFcgVGVjaCIsImVtYWlsIjoiY2xpZW50QGx0d3RlY2guaXQiLCJhdXRob3JpdHkiOiJ7XCJyb2xlXCI6W1wiY2xpZW50XCJdfSIsImlhdCI6MTcwMDQ3MDI5MywiZXhwIjoxNzAwNDczODkzfQ.-TzXgh2vzHVeP7OO2mBVLzZLwLDPiCeakdUNPuM-WqI


###
//Edit admin
PUT http://localhost:5005/moderator/edit/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiYWRtaW5AbHV4dXJ5Y2Fycy5pdCIsImlhdCI6MTY2MDg5MDk5NiwiZXhwIjoxNjYwODk0NTk2fQ.JuURSeIhtk2JMcpeB8gdME_1gCiveOWxcsGxEuHd8YA
Content-Type: application/json

{
    "name" : "ALEX",
    "address" : "123, Main Rd, Mannar",
    "website" : "travelagent.com",
    "phone_no" : "5678901235",
    "vat_id" : "ASDFGHJKLP098",
    "profile" : "1660632804460-LTWDentalCare-HomeLayout.png"
}

###
PUT http://localhost:5005/moderator/access_control/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiYXZhdGFyIjoiMTY2Nzc5MzI4ODEzMy02NjgtNjY4OTIwMl9hdmF0YXItcHJvZmlsZS1oZC1wbmctZG93bmxvYWQucG5nIiwidXNlcm5hbWUiOiJMVFcgVGVjaCIsImVtYWlsIjoiY2xpZW50QGx0d3RlY2guaXQiLCJhdXRob3JpdHkiOiJ7XCJyb2xlXCI6W1wiY2xpZW50XCJdfSIsImlhdCI6MTcwMDQ3MDI5MywiZXhwIjoxNzAwNDczODkzfQ.-TzXgh2vzHVeP7OO2mBVLzZLwLDPiCeakdUNPuM-WqI
Content-Type: application/json

{
    "is_deleted" : false
}

###
DELETE http://localhost:5005/moderator/delete/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYWRtaW5AbHV4dXJ5Y2Fycy5pdCIsImlhdCI6MTY2MDkxODQyOSwiZXhwIjoxNjYwOTIyMDI5fQ.riMbldUorNmyieMkWsWLWNpwknAuJayPy8__gQ5voK8

###
POST http://localhost:5005/moderator/forgot_password
Content-Type: application/json

{
    "email" : "client@ltwtech.it"
}

###
POST http://localhost:5005/moderator/reset_password/17/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZqdmZjMmsxNkBnbWFpbC5jb20iLCJpZCI6MTcsImlhdCI6MTY2NzM3ODYyMCwiZXhwIjoxNjY3Mzc4NjgwfQ.16tBQdQu6yhLWBwYslPEoW6cVGkfCO0cz_sCMBoInsI
Content-Type: application/json

{
    "password" : "12345"
}

###
PUT http://localhost:5005/moderator/change_password/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImF2YXRhciI6IjE2Njc1MzQ0OTg5MTEtZGVmYXVsdC1hdmF0YXIucG5nIiwidXNlcm5hbWUiOiJMVFcgVGVjaCIsImVtYWlsIjoiYWRtaW5AbHR3dGVjaC5pdCIsImF1dGhvcml0eSI6IntcInJvbGVcIjpbXCJhZG1pblwiLFwidXNlclwiXX0iLCJpYXQiOjE2Njc1NDA5NDAsImV4cCI6MTY2NzU0NDU0MH0.7WzgzSoqvWDm2SUvBsk0n_4qnRCtxiEzxoEtXdXOhcI
Content-Type: application/json

{
    "currentPassword" : "12345",
    "newPassword" : "1234"
}